[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { features = ["blocking", "cookies"] }
num-traits = "0.2"
num-derive = "0.4"
humantime = {}